# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-06-27 15:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_name', models.CharField(max_length=24, verbose_name='chapter name')),
                ('chapter_num', models.IntegerField(verbose_name='chapter number')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created time')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='recent update time')),
                ('content', models.TextField(max_length=10000)),
                ('reader_cnt', models.IntegerField(default=0, verbose_name='readers count')),
            ],
            options={
                'ordering': ['chapter_num'],
                'verbose_name': 'Chapter',
                'verbose_name_plural': 'Chapters',
            },
        ),
        migrations.CreateModel(
            name='Novel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('novel_name', models.CharField(max_length=24, verbose_name='novel name')),
                ('description', models.CharField(default='\u8fd9\u672c\u4e66\u61d2\u5f97\u4ecb\u7ecd\u81ea\u5df1', max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created time')),
                ('reader_cnt', models.IntegerField(default=0, verbose_name='readers count')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created'],
                'verbose_name': 'Novel',
                'verbose_name_plural': 'Novels',
            },
        ),
        migrations.AddField(
            model_name='chapter',
            name='novel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='novel.Novel'),
        ),
    ]
