# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-09 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_auto_20170706_2256'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='changepass_code',
            field=models.CharField(default=b'uvNLBno01NwevmM8', max_length=16),
        ),
    ]
